### ISSUE TITLE
testjob fails

### ISSUE THREAD

**Issue by kenneth59715** [cianfrocco-lab/COSMIC-CryoEM-Gateway#112]
I tried running the testjob, but it failed.  I think the batch job script is not getting
properly constructed.  Relion can't find input files.  Input files are present in
betagaltest, but ibrun gets executed one directory higher.  Maybe the cd in
the jobscript needs to go down one level?

**Comment by kenneth59715** [comment]
I think I can hack something into comet_relion_submit.py to cd down one more level.
Let me know if I should go ahead with that and retest before updating struts version for the
other ticket.

Kenneth

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - if you think you can fix it, go ahead. otherwise i can look this weekend / Monday of next week.

**Comment by monaw** [comment]
@kenneth59715 - FYI, the location of the remote script is in Mike's Google Doc

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - I saw that you had a test job running on comet, but there were no outputs being written. Despite this, it was running for 2 hours, so I killed it so we don't waste our allocation.

**Comment by mcianfrocco** [comment]
Job ID: NGBW-JOB-RELION_2D_CLASS_COMET-F21F97013CD64F86AEADD2A62F9B505F

**Comment by mcianfrocco** [comment]
hi @kenneth59715 - let me know when I can dig into the comet_relion_submit to fix some issues (unless of course you fix all the problems)

**Comment by kenneth59715** [comment]
Michael,

 Please go ahead with your fixes.

Kenneth

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - I think it should be fixed (or at least my test job is working). Test and see what happens.

**Comment by kenneth59715** [comment]
Michael,

 Job submit failed for me this error:

Sat Oct 27 18:52:07 PDT 2018 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE : Added to run queue.
Sat Oct 27 18:52:11 PDT 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE : Staging input files to COMET
Sat Oct 27 18:52:12 PDT 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE : Input files staged successfully
Sat Oct 27 18:52:13 PDT 2018 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE : java.lang.Exception: Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE {'resource': 'COMET', 'Tool': 'RELION_2D_CLASS_COMET', 'Task\\': 'ID=539', 'JobHandle': 'NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE', 'email': 'kyoshimoto@ucsd.edu', 'created\\': 'on=2018-10-27 18:51:24.0', 'cores': '15', 'Output': '(stderr.txt,stderr,UNKNOWN,UNKNOWN,UNKNOWN)', 'User\\': 'Name=046f34e64f8b7dc1015072dc7aa30a1a@ucsd.edu'} jobfinfo JobHandle (NGBW-JOB-RELION_2D_CLASS_COMET-8C1EC7931EFE4F0DB8DC0B6E53D103BE) submit command (sbatch batch_command.run 2>> batch_command.status) sbatch batch_command.run 2>> batch_command.status Error submitting job: submit_job start sbatch: error: bank_limit plugin: You are attempting to submit a job to a gpu partition with a wrong gres requested "(null)". Gres value should be gres=gpu:<type>:<number> or gres=gpu:<number> sbatch: error: Batch job submission failed: Invalid generic resource (gres) specification . 

Kenneth

**Comment by kenneth59715** [comment]
I'm still getting file not found errors like these:
Cannot read file particles/Micrographs/EMD-2984_0001_frames.mrcs It does not exi
st   
File: /share/apps/gpu/relion2/downloads/relion/src/image.h line: 157
[cli_2]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 2
Cannot read file particles/Micrographs/EMD-2984_0001_frames.mrcs It does not exi
st   
File: /share/apps/gpu/relion2/downloads/relion/src/image.h line: 157
[cli_4]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
Cannot read file particles/Micrographs/EMD-2984_0001_frames.mrcs It does not exist

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - i'm looking into it. Essentially, the metadata paths in the file betagaltest/particles.star don't match up.

**Comment by kenneth59715** [comment]
Yes, I think either the paths need betagaltest added in front or the job script
needs to cd down into the betagaltest.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - part of the problem is that the test data you have are in atypical directory structures relative to what we are 'used' to seeing now. There was a data structure reformatting that took place over the past year. 

I still need to deal with these type of fringe input data cases, but, in the meantime, you should be able to run this without problem: 

https://drive.google.com/file/d/1RlIptrGRRuz7_GgKu-fB1SU7DObvC0H-/view?usp=sharing

To use this: 
1. Download zipped file to your computer
2. Unzip directory
3. Use globus to upload entire 'Extract' directory into COSMIC2
4. Select the file: Extract/job007/particles.star as the input file
5. Submit 2D classification using: 
Particle diameter = 200
Pixel size = 3.68
Number of classes = 15
Number of iterations = 10
Inplane = 5
Search range = 5
Step size = 1

**Comment by mcianfrocco** [comment]
I'm waiting on this job to run on my account, but it *should* be fixed now with this type of input data structure.

**Comment by mcianfrocco** [comment]
I can confirm that the job ran successfully for me.

**Comment by kenneth59715** [comment]
Just to be clear, is betagaltest still expected to fail, but the new format test worked for you?
I am in the process of trying the new test.

**Comment by mcianfrocco** [comment]
Yes - betagaltest should fail but the new data should work.

**Comment by kenneth59715** [comment]
Still getting file read error:

Cannot read file Extract/job007/Movies/20170629_00021_frameImage.mrcs It does no
t exist
File: /share/apps/gpu/relion2/downloads/relion/src/image.h line: 157
[cli_4]: aborting job:
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 4
[comet-33-14.sdsc.edu:mpispawn_0][readline] Unexpected End-Of-File on file descr
iptor 5. MPI process died?
[comet-33-14.sdsc.edu:mpispawn_0][mtpmi_processops] Error while reading PMI socket. MPI process died?
[comet-33-14.sdsc.edu:mpispawn_0][child_handler] MPI process (rank: 4, pid: 25187) exited with status 1
Cannot read file Extract/job007/Movies/20170629_00021_frameImage.mrcs It does not existCannot read file Extract/job007/Movies/20170629_00021_frameImage.mrcs It does not exist



I think this one has to do with the way it was uploaded.  I uploaded the directory from
comet:/oasis/scratch-comet/kenneth/temp_project/shared/globustransfer/in3/Extract.
It looks like the portal or submit script copied everything from temp_project on down,
but the paths start with Extract, so the files are not found.

Kenneth

**Comment by mcianfrocco** [comment]
Hi @kenneth59715 - yes, I should have explicitly stated that you should have navigated using the globus directory path to /oasis/scratch-comet/kenneth/temp_project/shared/globustransfer/in3/, and then selecting 'Extract' as the upload. 

This is the same problem as before, handling these relative paths still isn't worked out quite right.

Try reuploading and then see if it works.

Mike

**Comment by kenneth59715** [comment]
Okay, with correct path for Extract, I'm getting past the file not found, but it is getting killed
with a signal 15 in iteration 5.  No output.tar.gz

**Comment by mcianfrocco** [comment]
Ok - I think I fixed it (!) finally. This should be a general solution, meaning that no matter what type of upstream path the user brought with the input star file, the code should run.

Kenneth - try your test again as you originally did when it failed.

**Comment by kenneth59715** [comment]
I tried running an old test job (not sure I got the parameters the same).
That gave this error:
Fri Dec 21 09:17:50 PST 2018 > QUEUE : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-A772018B0CDF48C5BB41D1E192801392 : Added to run queue.
Fri Dec 21 09:17:57 PST 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-A772018B0CDF48C5BB41D1E192801392 : Staging input files to COMET
Fri Dec 21 09:17:58 PST 2018 > INPUTSTAGING : SUCCESS : NGBW-JOB-RELION_2D_CLASS_COMET-A772018B0CDF48C5BB41D1E192801392 : Input files staged successfully
Fri Dec 21 09:17:59 PST 2018 > SUBMITTING : ERROR : NGBW-JOB-RELION_2D_CLASS_COMET-A772018B0CDF48C5BB41D1E192801392 : java.lang.Exception: Error submitting job: /projects/cosmic2/gateway/workspace/NGBW-JOB-RELION_2D_CLASS_COMET-A772018B0CDF48C5BB41D1E192801392 . Traceback (most recent call last): File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 319, in <module> relion_command,outdir,runhours,nodes,numiters,worksubdir=prepareRelionRun(args['commandline']) File "/home/cosmic2/COSMIC-CryoEM-Gateway/remote_scripts/comet_relion_submit.py", line 123, in prepareRelionRun os.makedirs('Class2D_cosmic') File "/share/apps/compute/python-2.7.14/lib/python2.7/os.py", line 157, in makedirs mkdir(name, mode) OSError: [Errno 17] File exists: 'Class2D_cosmic'

What are the correct parameters for the Extract test job?

Kenneth

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by mcianfrocco** [comment]
It doesn't really matter for testing, but here are some you could use: 

<img width="734" alt="example_params" src="https://user-images.githubusercontent.com/1464469/50358349-f8a57580-0526-11e9-8275-c2c2fec17b88.png">

Go ahead and try again

**Comment by mcianfrocco** [comment]
I've done more testing and this continues to work for me - I'm going to close it for now.
